console.log("***Step 1***");
var myFullname;
console.log("myFullname");
myFullname="Megha Kulkarni";
console.log("my full name is:",myFullname);
myFullname="Megha Kishor Kulkarni";
console.log("My first name,middle name,last name is:",myFullname);
console.log("***Step 2***");
 var mylove="I love only js";
 console.log(mylove);
 console.log("***Step 3***");
 var firstName="Megha";
 var lastName="Kulkarni";
 var age="20";
 var address="Mangalwedha Solapur";
 var pincode="413305";
 var gender="Female";
 var isMarried="No";
 console.log("MyName is:",firstName,"my Surname is:",lastName,"my Age is:",age,"My pin code is:",pincode,"my address is:",address,"Married:",isMarried);