console.log("Swapping Two Numbers");
var n1=500;
var n2=400;
console.log("before swapping numbers");
console.log(n1,n2);
var temp=n1;
n1=n2;
n2=temp;
console.log("after swapping numbers");
console.log(n1,n2);
console.log("typeof n1:",typeof n1);
console.log("typeof n2:",typeof n2);

console.log("**Different Program**");
var sita="sita";
var geeta="geeta";
console.log("before swapping name");
console.log(sita,geeta);
var temp=sita;
sita=geeta;
geeta=temp;
console.log("after swapping name");
console.log(sita,geeta);
console.log("typeof sita:",typeof sita);
console.log("typeof geeta:",typeof geeta);

console.log("**Different program**");
var city="pune";
var city1="mumbai";
console.log("before swapping city");
console.log(city,city1);
var temp=city;
city=city1;
city1=temp;
console.log("after swapping city");
console.log(city,city1);
console.log("typeof city:",typeof city);
console.log("typeof city1:",typeof city1);

console.log("**Different program**");
var name="Megha";
var surname="Kulkarni";
console.log("before swapping name and surname");
console.log(name,surname);
var temp=name;
name=surname;
surname=temp;
console.log("after swapping name and surname");
console.log(name,surname);
